create table Lavanderia
(
    id                    bigint generated by default as identity ,
    nome                  varchar(50) NOT NULL,
    endereco              varchar(100) NOT NULL,
    numero        numeric (1000) NOT NULL,
    bairro                varchar(30) NOT NULL,
    zona                  varchar(20) NOT NULL,
    primary key (id)
);